[theme]
base = "dark"
primaryColor = "#9467bd"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#fafafa"
font = "sans serif"

[server]
maxUploadSize = 10
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
